package corba;


/**
* corba/BrokerClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BrokerClient.idl
* Thursday, May 14, 2015 9:01:16 PM CST
*/

public interface BrokerClientOperations 
{
  String[] listRoom (String city, String hotel);
  double bookRoom (String city, String hotel, String type, String checkin, String checkout);
  String insertInfo (String id, String name, String cno, String email, String hotel);
} // interface BrokerClientOperations
