package corba;

/**
* corba/BrokerClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BrokerClient.idl
* Thursday, May 14, 2015 9:01:16 PM CST
*/

public final class BrokerClientHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.BrokerClient value = null;

  public BrokerClientHolder ()
  {
  }

  public BrokerClientHolder (corba.BrokerClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.BrokerClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.BrokerClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.BrokerClientHelper.type ();
  }

}
