package corba;


/**
* corba/BrokerClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BrokerClient.idl
* Thursday, May 14, 2015 9:01:16 PM CST
*/

public interface BrokerClient extends BrokerClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BrokerClient
