package corba;


/**
* corba/roomrateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BrokerClient.idl
* Thursday, May 14, 2015 9:01:16 PM CST
*/

public final class roomrateHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public roomrateHolder ()
  {
  }

  public roomrateHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.roomrateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.roomrateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.roomrateHelper.type ();
  }

}
